/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BlockRewardMock } from "./BlockRewardMock";
export type { ConsensusMock } from "./ConsensusMock";
export type { EternalStorageProxyMock } from "./EternalStorageProxyMock";
export type { ProxyStorageMock } from "./ProxyStorageMock";
export type { VotingMock } from "./VotingMock";
