/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBlockReward,
  IBlockRewardInterface,
} from "../../interfaces/IBlockReward";

const _abi = [
  {
    constant: false,
    inputs: [],
    name: "onCycleEnd",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBlockReward__factory {
  static readonly abi = _abi;
  static createInterface(): IBlockRewardInterface {
    return new Interface(_abi) as IBlockRewardInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBlockReward {
    return new Contract(address, _abi, runner) as unknown as IBlockReward;
  }
}
