/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBlockReward__factory } from "./IBlockReward__factory";
export { IConsensus__factory } from "./IConsensus__factory";
export { IVoting__factory } from "./IVoting__factory";
