/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IVoting, IVotingInterface } from "../../interfaces/IVoting";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "validators",
        type: "address[]",
      },
    ],
    name: "onCycleEnd",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVoting__factory {
  static readonly abi = _abi;
  static createInterface(): IVotingInterface {
    return new Interface(_abi) as IVotingInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IVoting {
    return new Contract(address, _abi, runner) as unknown as IVoting;
  }
}
