/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EternalStorage } from "./EternalStorage";
export type { EternalStorageProxy } from "./EternalStorageProxy";
