/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EternalStorage__factory } from "./EternalStorage__factory";
export { EternalStorageProxy__factory } from "./EternalStorageProxy__factory";
