/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBlockReward } from "./IBlockReward";
export type { IConsensus } from "./IConsensus";
export type { IVoting } from "./IVoting";
