/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BlockRewardMock__factory } from "./BlockRewardMock__factory";
export { ConsensusMock__factory } from "./ConsensusMock__factory";
export { EternalStorageProxyMock__factory } from "./EternalStorageProxyMock__factory";
export { ProxyStorageMock__factory } from "./ProxyStorageMock__factory";
export { VotingMock__factory } from "./VotingMock__factory";
